version: '3'

services:
  api:
    build: ./packages/api
    container_name: api
    volumes:
      - ./packages/api:/app
    ports:
      - '4000:4000'
    links:
      - cache
    depends_on:
      - cache
    environment:
      - VIRTUAL_HOST=api.quick.journey

  cache:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'

  web:
    build: ./packages/web
    container_name: web
    volumes:
      - ./packages/web:/app
    ports:
      - '3000:3000'
    environment:
      - VIRTUAL_HOST=quick.journey

  shared:
    build: ./
    container_name: shared
    volumes:
      - ./:/var/www
    ports:
      - '8888:8888'

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
