export enum PlaceType {
  AIRPORT = 'airport',
  ATM = 'atm',
  BAKERY = 'bakery',
  BANK = 'bank',
  BAR = 'bar',
  CAFE = 'cafe',
  CAR_REPAIR = 'car_repair',
  CITY_HALL = 'city_hall',
  DENTIST = 'dentist',
  DOCTOR = 'doctor',
  DRUGSTORE = 'drugstore',
  GAS_STATION = 'gas_station',
  GROCERY = 'grocery',
  GYM = 'gym',
  HOSPITAL = 'hospital',
  LIBRARY = 'library',
  POLICE = 'police',
  POST_OFFICE = 'post_office',
  RESTAURANT = 'restaurant',
  STORE = 'store',
  SUPERMARKET = 'supermarket',
  TRAIN_STATION = 'train_station',
}
